story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1', include('story1.urls')),
    path('story6', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('', include('story8.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('',views.accord,name='accord'),
    path('register/', views.register, name="register"),
     path('login/', views.loginCus, name='login'),
    path('logout/', views.logoutCus, name='logout'),
]

story7/models.py
from django.db import models

# Create your models here.

story7/forms.py
from django.contrib.auth.models import User
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(
        label="Username ",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'example: ilma',
                'name': 'username',
            }
        ),
        max_length=16
    )
    email = forms.EmailField(
        label="Email ",
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'name': 'email',
            }
        )
    )
    password1 = forms.CharField(
        label="Password ",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'name': 'password',
            }
        )
    )

class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label="Username: ",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'name': 'username',
            }
        )
    )
    password = forms.CharField(
        label="Password: ",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'name': 'username',
            }
        )
    )

story7/views.py
from django.http import response,HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import RegisterForm, LoginForm


# Create your views here.
def accord(request):
    return render(request,'story7/accordion.html')

def register(request):
    if request.user.is_authenticated:
        return redirect('/story7/')
    else:
        form = RegisterForm()
        if request.method == "POST":
            form_input = RegisterForm(request.POST)
            if form_input.is_valid():
                username_input = request.POST['username']
                password_input = request.POST['password1']
                try:
                        new_user = User.objects.create_user(
                        username=username_input, email=request.POST['email'], password=password_input)
                        new_user.save()
                        user_login = authenticate(
                            request, username=username_input, password=password_input)
                        login(request, user_login)
                        return redirect('/story7/')
                except:
                        return render(request, 'story7/error.html')
                 
            else:
                return render(request, 'story7/register.html', {'form': form_input})
        return render(request, 'story7/register.html', {'form': form})

def loginCus(request):
    if request.user.is_authenticated:
        return redirect('/story7/')
    form = LoginForm()
    if request.method == "POST":
        data = LoginForm(request.POST)
        if data.is_valid():
            username_input = request.POST['username']
            password_input = request.POST['password']
            user_login = authenticate(
                request, username=username_input, password=password_input)
            if user_login is None:
                return render(request, 'story7/login.html', {'status': 'failed', 'form': form})
            else:
                login(request, user_login)
                return redirect('/story7/')
        else:
            return render(request, 'story7/login.html', {'status': 'failed', 'form': data})
    else:
        return render(request, 'story7/login.html', {'form': form})

@login_required
def logoutCus(request):
    logout(request)
    return redirect('/story7/')

story7/templates/story7/accordion.html
{% extends 'story7/base.html' %}
{% load static %}

{% block title %}Story9{% endblock %}
{% block body %}
{% if not user.is_authenticated %}
<div class="jumbotron">
    <h1 class="display-4">Selamat Datang!</h1>
    <hr class="my-4">
    <p>Silahkan login untuk melihat isi konten</p>
    <a class="btn btn-light btn-lg" href="{% url 'story7:login'%}" role="button">LOGIN</a>
</div>
{% endif %}
{% if user.is_authenticated %}
<div class="jumbotron">
    <h1 class="display-4">Selamat Datang {{ user }}!</h1>
    <hr class="my-4">
    <p>Terima kasih sudah berkunjung <br> Jangan lupa untuk logout ^_^</p>
    <a class="btn btn-light btn-lg" href="{% url 'story7:logout'%}" role="button">LOGOUT</a>
</div>
{% endif %}
{% if user.is_authenticated %}
<h1>Get To Know Ilma</h1><br>
<div class="container">
    <div class="card mb-3">
        <div class="card-header">
            <h3>Aktivitas Saat Ini <button type="button" class="btn btn-light btn-sm up ">Up</button>
                <button type="button" class="btn btn-light btn-sm down">Down</button> </h3>
        </div>
        <div id="ac_1" class="card-body">Aktivitas yang saya lakukan saat ini adalah mengerjakan tugas ;-; ,
            belajar, dan
            rapat. aka KURA-KURA. Got no time to play some games bruh.
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h3>Pengalaman Organisasi <button type="button" class="btn btn-light btn-sm up">Up</button>
                <button type="button" class="btn btn-light btn-sm down">Down</button></h3>
        </div>
        <div id="ac_2" class="card-body">
            <li>Ketua Koordinator Harian II Subseksi Kemasyarakatan SMAN8 Jakarta</li><br>
            <li>Ketua Ceramah Keputrian Subseksi Rohani Islam SMAN8 Jakarta</li><br>
            <li>Staf BEM Pengmas Fasilkom UI 2020</li>
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h3>Pengalaman Kepanitiaan <button type="button" class="btn btn-light btn-sm up">Up</button>
                <button type="button" class="btn btn-light btn-sm down">Down</button></h3>
        </div>
        <div id="ac_3" class="card-body">
            <li>Staf Mentor dan Peserta BETIS 2020</li><br>
            <li>Project Officer BETIS 2021</li><br>
            <li>Humas Bazar For Charity</li><br>
            <li>Humas Bakti Sosial In Tesis</li><br>
            <li>Acara 8Mission</li><br>
            <li>Humas Lampion</li><br>
            <li>Humas 8Peduli Kasih</li><br>
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <h3>Prestasi <button type="button" class="btn btn-light btn-sm up">Up</button>
                <button type="button" class="btn btn-light btn-sm down">Down</button></h3>
        </div>
        <div id="ac_4" class="card-body">
            ZERO
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

story7/templates/story7/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="shortcut icon" href="#">
    <link rel="stylesheet" href="{% static 'story7/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    {% block body %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="{% static 'story7/script.js' %}"></script>
</body>

</html>

story7/templates/story7/error.html
{% extends 'story7/base.html' %}
{% block title %}Exists{% endblock %}
{% block body %}
<div class="alert alert-warning" role="alert" style="text-align: center">
    <h1>Username already <strong>exists</strong>! Please try another one</h1><br>
    <a class="btn btn-warning btn-lg" href="{% url 'story7:register'%}" role="button">SIGN UP</a>
</div>
{% endblock %}

story7/templates/story7/login.html
{% extends 'story7/base.html' %}
{% block title %}Form Login{% endblock %}
{% block body %}
<div class="container">
    <form class="formLogin align-self-center" action="" method="POST">
        {% csrf_token %}
        <h1 style="text-align: center;">LOGIN</h1>
        <div class="form-group">
            <label for="username">
                {{form.username.label}}
            </label>
            {{form.username}}
        </div>
        <br>
        <div class="form-group">
            <label for="password">
                {{form.password.label}}
            </label>
            {{form.password}}
        </div>
        <br>
        <button type="submit" style="width: 20%;" class="btn btn-dark">Submit</button>
    </form>
    <a href="{% url 'story7:register'%}">Didn't have account?</a>
    {% if status == 'failed' %}
    <div class="alert alert-danger" role="alert" style="text-align: center">
        <h1 style="text-align: center">
            Incorrect Username or Password.
        </h1>
    </div>
</div>
{% endif %}
{% endblock %}

story7/templates/story7/register.html
{% extends 'story7/base.html' %}
{% block title %}Form Register{% endblock %}
{% block body %}
<div class="container">
    <form class=" align-self-center" action="" method="POST">
        {% csrf_token %}
        <h1 style="text-align: center;">REGISTER</h1>
        {{form}}
        <br>
        <button type="submit" style="width: 20%;" class="btn btn-dark">Submit</button>
    </form>

    {% if form.errors %}
    <div class="error">
        <p><span>Terjadi Error!</span></p>
        <ul>
            {% for key,value in form.errors.items %} {% for error in value %}
            <li>{{ error }}</li>
            {% endfor %} {% endfor %}
        </ul>
    </div>
    {% endif %}
    <a href="{% url 'story7:login'%}">Have an account?</a>
</div>
{% endblock %}