story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1', include('story1.urls')),
    path('story6', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('', include('story8.urls')),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('',views.createKegiatan,name='kegiatan'),
    path('create/<int:siswa_id>', views.createSiswa, name='create'),
]

story6/models.py
from django.db import models

# Create your models here.

class listKegiatan(models.Model):
	namaKegiatan = models.TextField(max_length=300)

	def __str__(self):
		return self.namaKegiatan

class listSiswa(models.Model):
	namaSiswa = models.TextField(max_length=300)
	kegiatan = models.ForeignKey(listKegiatan, on_delete=models.CASCADE)

	def __str__(self):
		return self.namaSiswa



# Create your models here.

story6/forms.py
from django.forms import ModelForm
from .models import listKegiatan,listSiswa
from django import forms

class formKegiatan(forms.Form):
	namaKegiatan = forms.CharField(max_length=300,required=True)

class formSiswa(forms.Form):
	namaSiswa = forms.CharField(max_length=300)
        

story6/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.http import HttpResponseRedirect

# Create your views here.
def createKegiatan(request):
	kegiatan= listKegiatan.objects.all()
	kegiatann= formKegiatan(request.POST or None)
	context={
		'kegiatan':kegiatan,
		'kegiatann':kegiatann
	}
	if request.method=='POST':
		if kegiatann.is_valid():
			kegiatan.create(
				namaKegiatan=kegiatann.cleaned_data.get('namaKegiatan')
				)
	return render(request,'story6/kegiatan.html',context)

def createSiswa(request, siswa_id):
	siswa= listKegiatan.objects.get(id=siswa_id)
	siswaTarget = listSiswa.objects.all()
	form_siswa = formSiswa(request.POST or None)
	context={
		'siswa':siswa,
		'form_siswa':form_siswa,
		'siswa_target':siswaTarget,
	}
	if request.method=='POST':
		if form_siswa.is_valid():
			siswaTarget.create(
					namaSiswa=form_siswa.cleaned_data.get('namaSiswa'),
					kegiatan=siswa
				)
	return render(request,'story6/jadwal_siswa.html',context)

story6/templates/story6/jadwal_siswa.html
<!DOCTYPE html>
<html>

<head>
	<title>Kegiatan</title>
	{% include "story6/navi.html" %}
</head>

<body>
	<h2>Jadwal Kegiatan</h2>

	<form method="POST">
		{% csrf_token %}
		<table>
			{{form_siswa.as_table}}
		</table>
		<button type="Submit" name="submit">Submit</button>

		<table class="table table-light table-striped">
			<thead>
				<tr>
					<th scope="col">Nama Siswa</th>
				</tr>
			</thead>
			<tbody>
				{% for sis in siswa_target %}
				<tr>
					{% if sis.kegiatan == siswa %}
					<th scope="row">{{sis.namaSiswa}}</th>
					{% endif %}
				</tr>
			</tbody>
			{% endfor %}
</body>

</html>

story6/templates/story6/kegiatan.html
<!DOCTYPE html>
<html>

<head>
	<title>Kegiatan</title>
	{% include "story6/navi.html" %}
</head>

<body>
	<h2>Jadwal Kegiatan</h2>

	<form method="POST">
		{% csrf_token %}
		<table>
			{{kegiatann.as_table}}
		</table>
		<button type="Submit" name="submit">Submit</button>

		<table class="table table-light table-striped">
			<thead>
				<tr>
					<th scope="col">Nama Kegiatan</th>
				</tr>
			</thead>
			<tbody>
				{% for keg in kegiatan %}
				<tr>
					<th scope="row">{{keg.namaKegiatan}}</th>
					<td><a href="{% url 'story6:create' siswa_id=keg.id %}" class="btn btn-primary">Lihat/Add Siswa</a>
					</td>
				</tr>
			</tbody>
			{% endfor %}
</body>

</html>

story6/templates/story6/navi.html
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="shortcut icon" href="#">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/story6">Kegiatan</a>
        </li>
      </ul>
    </div>
  </nav>
  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>