homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('skill', views.skill, name='skill'),
    path('index', views.index, name='index'),
    path('list',views.list,name='list'),
    path('create',views.create,name='create'),
    path('delete/<int:delete_id>',views.delete,name='delete'),
    path('detail/<int:id_detail>', views.detail, name='detail'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1', include('story1.urls')),
    path('story6', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('', include('story8.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.first, name='first'),
]

homepage/models.py
from django.db import models

class Course(models.Model):
    course = models.CharField(max_length=50)
    lecturer = models.CharField(max_length=50)
    sks = models.IntegerField(null=True)
    desc = models.TextField(null=True)
    term = models.CharField(max_length=50,null=True)
    classroom = models.CharField(max_length=30,null=True)


    def __str__(self):
        return "{}.{}".format(self.id,self.course)

# Create your models here.

homepage/forms.py
from django import forms

from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = [
            'course',
            'lecturer',
            'sks',
            'desc',
            'term',
            'classroom',
        ]

homepage/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Course
from .forms import CourseForm

def index(request):
    return render(request, 'index.html')
def skill(request):
    return render(request,'skill.html')
def list(request):
    all_course = Course.objects.all()
    context = {
        'page_title':'Courses',
        'all_course':all_course
    }
    return render(request,'courses.html',context)

def create(request):
    course_form = CourseForm(request.POST or None)

    if request.method == 'POST' :
        if course_form.is_valid():
            course_form.save()
        return redirect('homepage:list')

    context = {
        "page_title":"Add Course",
        "course_form":course_form,
    }
    return render(request,'create.html',context)

def delete(request,delete_id):
    Course.objects.filter(id=delete_id).delete()
    return redirect('homepage:list')

def detail(request, id_detail) :
   id_course = Course.objects.get(id=id_detail)
   return render(request, 'detail.html', {'course': id_course})

# Create your views here.

homepage/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="shortcut icon" href="#">

    <title>
        {% block title %}

        {% endblock title %}
    </title>
</head>

<body>
    <div class="container">
        {% block contents %}

        {% endblock contents %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

homepage/templates/courses.html
{% extends "base.html" %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<h1>{{page_title}}</h1>
<table class="table ">
    <thead>
        <tr>
            <th scope="col">Number</th>
            <th scope="col">Course</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for course in all_course %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><a href="{% url 'homepage:detail' course.id %}">{{course.course}}</a></td>
            <td><a class="btn btn-danger" href="{% url 'homepage:delete' delete_id=course.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'homepage:create'%}">Add Course</a>
{% endblock contents %}

homepage/templates/create.html
{% extends "base.html" %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<form method="POST">
    {% csrf_token %}
    <table>
        {{course_form.as_table}}
    </table>
    <button type="Submit">Submit</button>
</form>
{% endblock contents %}

homepage/templates/detail.html
{% extends "base.html" %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<h1>{{course.course}}</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Lecturer</th>
            <th scope="col">SKS</th>
            <th scope="col">Description</th>
            <th scope="col">Term</th>
            <th scope="col">Class Room</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{course.lecturer}}</td>
            <td>{{course.sks}}</td>
            <td>{{course.desc}}</td>
            <td>{{course.term}}</td>
            <td>{{course.classroom}}</td>
        </tr>
    </tbody>
</table>
{% endblock contents %}

homepage/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homepage/style.css' %}" />
    <link rel="shortcut icon" href="#">
    <title>Hello</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="profile">
        <div class="container">
            <img class="circular-image" src="{% static 'homepage/Ilma.jpg' %}" alt="Photo of me">
            <h1 class="display-4">Ilma Alpha Mannix</h1>
            <p class="lead">Computer Science Student at University of Indonesia</p>
        </div>
    </div>
    <div class="about" id="about">
        <div class="container">
            <h1>About</h1>
            <p>Hello everyone! <br>This is Ilma and I just wanna say Welcome to my page! I am a second year computer
                science student at University of Indonesia. My NPM is 1906351045 As a comp science student, I have
                a great interest in Web Development, besides that I also like sleeping.<br>Don't forget to check out
                my<a href="https://www.instagram.com/ilmamannix/"> social media</a> :)</p>
        </div>
    </div>

    <div class="education" id="education">
        <div class="container">
            <h1>Education</h1>
            <ul style="list-style-type:square;">
                <li>Elementary School</li>
                <p>SDIT Abata <br> SDN 09 Pg Jakarta</p>
                <li>Junior High School</li>
                <p>SMPN 19 Jakarta</p>
                <li>High School</li>
                <p>SMAN 8 Jakarta</p>
            </ul>
        </div>
    </div>

    <!-- Footer -->
    <footer class="page-footer" id="contact">
        <div class="container">
            <h1>Contact <a href="https://www.instagram.com/ilmamannix/">
                    <img class="ig" src="{% static 'homepage/ig.png' %}">
                </a></h1>
        </div>
    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>

homepage/templates/navbar.html
{% load static %}

<!DOCTYPE html>

<head>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparant fixed-top">
        <div class="container">
            <a class="navbar-brand" href="">
                <img class="logo" src="{% static 'homepage/logo.jpg' %}">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage:list'%}">Courses<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'story1:first' %}">Story1<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage:index' %}#about">About<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage:index'%}#education">Education<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'homepage:skill'%}#skill">Skill<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#contact">Contact<span class="sr-only">(current)</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

</body>

homepage/templates/skill.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homepage/style.css' %}" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
    <link rel="shortcut icon" href="#">
    <title>Hello</title>
</head>

<body>
    {% include "navbar.html" %}
    <div class="profile">
        <div class="container">
            <img class="circular-image" src="{% static 'homepage/Ilma.jpg' %}" alt="Photo of me">
            <h1 class="display-4">Ilma Alpha Mannix</h1>
            <p class="lead">Computer Science Student at University of Indonesia</p>
        </div>
    </div>

    <div class="skills" id="skill">
        <div class="container">
            <h1>Skill</h1>
            <div class="bar">
                <div class="info">
                    <span>PYTHON</span>
                </div>
                <div class="progress-line python"><span></span></div>
            </div>
            <div class="bar">
                <div class="info">
                    <span>JAVA</span>
                </div>
                <div class="progress-line java"><span></span></div>
            </div>
            <div class="bar">
                <div class="info">
                    <span>LEADERSHIP</span>
                </div>
                <div class="progress-line leadership"><span></span></div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="page-footer" id="contact">
        <div class="container">
            <h1>Contact <a href="https://www.instagram.com/ilmamannix/">
                    <img class="ig" src="{% static 'homepage/ig.png' %}">
                </a></h1>
        </div>
    </footer>
    <!-- Footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>